// This file is automatically generated. Do not edit it directly.
// NOTE: Bu fayl avtomatik yaratilgan. Asosiy Supabase client uchun @/lib/supabaseClient dan foydalaning.
import { supabase } from "@/lib/supabaseClient";

// Re-export for backward compatibility
export { supabase };